apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-1
  labels:
    app: youtube-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: youtube-1
  template:
    metadata:
      labels:
        app: youtube-1
    spec:
      containers:
      - name: youtube-1
        image: balajeevidesh4010/youtube-1:2
        ports:
        - containerPort: 3000
