apiVersion: v1
kind: Service
metadata:
  name: youtube-1
  labels:
    app: youtube-1
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: youtube-1
  type: LoadBalancer
