apiVersion: v1
kind: Service
metadata:
  name: youtube
  labels:
    app: youtube
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: youtube
  type: LoadBalancer
