apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube
  labels:
    app: youtube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: youtube
  template:
    metadata:
      labels:
        app: youtube
    spec:
      containers:
      - name: youtube
        image: balajeevidesh4010/youtube:3
        ports:
        - containerPort: 3000
